serviceMonitors:
  - name: test
    namespace: test
    overrideNamespace: false
    annotations:
      somekey: somevalue
    labels:
      release: kube-prometheus-stack
    jobLabel: mylabel
    targetLabels:
      - test
    podTargetLabels:
      - test
    selector:
      somekey: somevalue
    endpoints:
      - port: http
        path: /metrics
        scheme: http
        interval: 30s
        scrapeTimeout: 30s
        honorLabels: true
        metricRelabelings: []
        relabelings: []
