{{- range .Values.serviceMonitors }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .name }}
  namespace: {{ ternary .namespace $.Release.Namespace .overrideNamespace }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  jobLabel: {{ .jobLabel }}
  {{- with .targetLabels }}
  targetLabels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .podTargetLabels }}
  podTargetLabels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .endpoints }}
  endpoints:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .selector }}
  selector:
    matchLabels:
      {{- toYaml . | nindent 6 }}
  {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .namespace }}
---
{{- end }}
